"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import environs
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environs.Env()
env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY", default="insecure-dev-key")
_USING_TESTS = any(arg in ("test", "pytest") for arg in sys.argv)
if not DEBUG and not _USING_TESTS and SECRET_KEY == "insecure-dev-key":
    raise RuntimeError("DJANGO_SECRET_KEY is required when DEBUG=False")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

# CSRF trusted origins
_default_csrf_trusted = []
for _h in ALLOWED_HOSTS:
    if _h == "*":
        continue
    if _h.startswith(("http://", "https://")):
        _default_csrf_trusted.append(_h)
        continue
    _default_csrf_trusted.append(f"http://{_h}")
    _default_csrf_trusted.append(f"https://{_h}")
    if _h in ("localhost", "127.0.0.1"):
        # Common local ports (nginx 8080, django 8001)
        _default_csrf_trusted.extend([
            f"http://{_h}:8080",
            f"http://{_h}:8001",
        ])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=_default_csrf_trusted)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "apps.botapp",
    "apps.common",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RequestIdMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

APPEND_SLASH = True


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env.bool("USE_SQLITE", default=False):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    database_url = env.str("DATABASE_URL", default=None)
    if database_url:
        DATABASES = {
            "default": dj_database_url.parse(database_url, conn_max_age=600, ssl_require=False)
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env("POSTGRES_DB"),
                "USER": env("POSTGRES_USER"),
                "PASSWORD": env("POSTGRES_PASSWORD"),
                "HOST": env("DB_HOST"),
                "PORT": env("DB_PORT"),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "uz"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR.joinpath("staticfiles")

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.joinpath("media")

# Upload limits (Telegram updates are small; keep a sensible cap)
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int("DJANGO_MAX_BODY_BYTES", default=2_000_000)
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int("DJANGO_MAX_BODY_BYTES", default=2_000_000)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
LOG_LEVEL = env.str("LOG_LEVEL", default="INFO").upper()
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)
LOG_BACKUP_COUNT_DAYS = env.int("LOG_BACKUP_COUNT_DAYS", default=14)
LOG_ROTATE_UTC = env.bool("LOG_ROTATE_UTC", default=True)
def _timed_file_handler(filename: str) -> dict:
    return {
        "class": "logging.handlers.TimedRotatingFileHandler",
        "formatter": "json",
        "filters": ["request_id"],
        "filename": str(LOG_DIR / filename),
        "when": "midnight",
        "backupCount": LOG_BACKUP_COUNT_DAYS,
        "utc": LOG_ROTATE_UTC,
    }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "core.logging_utils.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_id"],
        },
        "django_file": _timed_file_handler("django.log"),
        "celery_file": _timed_file_handler("celery.log"),
        "celery_beat_file": _timed_file_handler("celery_beat.log"),
        "celery_task_file": _timed_file_handler("celery_task.log"),
        "flower_file": _timed_file_handler("flower.log"),
    },
    "filters": {
        "request_id": {"()": "core.logging_utils.RequestIdFilter"},
    },
    "loggers": {
        "django": {"handlers": ["console", "django_file"], "level": LOG_LEVEL, "propagate": False},
        "django.request": {"handlers": ["console", "django_file"], "level": LOG_LEVEL, "propagate": False},
        "core": {"handlers": ["console", "django_file"], "level": LOG_LEVEL, "propagate": False},
        "celery": {"handlers": ["console", "celery_file"], "level": LOG_LEVEL, "propagate": False},
        "celery.beat": {"handlers": ["console", "celery_beat_file"], "level": LOG_LEVEL, "propagate": False},
        "celery.task": {"handlers": ["console", "celery_task_file"], "level": LOG_LEVEL, "propagate": False},
        "flower": {"handlers": ["console", "flower_file"], "level": LOG_LEVEL, "propagate": False},
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
}

# Celery logging behavior
CELERYD_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# Celery
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default="redis://redis:6379/1")
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND", default="redis://redis:6379/2")
CELERY_ACCEPT_CONTENT = env.list("CELERY_ACCEPT_CONTENT", default=["json"])
CELERY_TASK_SERIALIZER = env.str("CELERY_TASK_SERIALIZER", default="json")
CELERY_RESULT_SERIALIZER = env.str("CELERY_RESULT_SERIALIZER", default="json")
CELERY_TIMEZONE = env.str("CELERY_TIMEZONE", default=TIME_ZONE)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = env.int("CELERY_TASK_TIME_LIMIT", default=300)

# Security hardening when not in DEBUG
if not DEBUG:
    SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", True)
    CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
